---
title: "Analysis"
output: html_document
date: '2023-04-14'
---

```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
```

## First exploratory data 
```{r}

```

```{r Chris analysis}
personen <- read_delim(file = "data/protected_data/personen.csv", col_names = TRUE)
personen_hist <- read_delim(file = "data/protected_data/personen_hist.csv", col_names = TRUE)
firmen <- read_delim(file = "data/protected_data/firmen.csv", col_names = TRUE)
firmen_hist <- read_delim(file = "data/protected_data/firmen_hist.csv", col_names = TRUE)
relationen_person_firma <- read_delim(file = "data/protected_data/relationen_person_firma.csv", col_names = TRUE)
relationen_person_firma_hist <- read_delim(file = "data/protected_data/relationen_person_firma_hist.csv", col_names = TRUE)
relationen_firma_firma <- read_delim(file = "data/protected_data/relationen_firma_firma.csv", col_names = TRUE)
head(personen)
head(relationen_person_firma)

# Adjust data types


# Adjust "branche"
firmen$branche <- gsub(firmen$wz_code, replacement = "", pattern = "\\{|\\}")
firmen$branche <- strsplit(firmen$branche, ",")
firmen$branche <- lapply(firmen$branche, as.numeric)
firmen$branche <- lapply(firmen$branche, min)
firmen$branche <- substr(firmen$branche,1,2)
firmen <- firmen %>% mutate(branche = as.numeric(branche)) %>% 
  mutate(branchen_code = case_when(branche < 05 ~ "A", 
                                   branche < 10 ~ "B", 
                                   branche < 35 ~ "C", 
                                   branche < 45 ~ "E", 
                                   branche < 49 ~ "G", 
                                   branche < 55 ~ "H", 
                                   branche < 58 ~ "I", 
                                   branche < 64 ~ "J",
                                   branche < 68 ~ "K", 
                                   branche < 69 ~ "L", 
                                   branche < 77 ~ "M", 
                                   branche < 84 ~ "N", 
                                   branche < 85 ~ "O", 
                                   branche < 86 ~ "P", 
                                   branche < 90 ~ "Q", 
                                   branche < 97 ~ "R", 
                                   branche < 99 ~ "T", 
                                   branche == 99 ~ "U"))

firmen$ma <- strsplit(firmen$mitarbeiter_staffel, ",")
firmen$ma <- lapply(firmen$ma, tail, n = 1L)
firmen$ma <- gsub(firmen$ma,  replacement = "", pattern = "\"")
firmen$year_ma <- strsplit(firmen$ma,  "=>")
firmen$ma_range <- lapply(firmen$year_ma, tail, n = 1L)
firmen$year_ma <- lapply(firmen$year_ma, head, n = 1L)



# Definieren der URL und Parameter für die OpenStreetMap-API
url <- "https://nominatim.openstreetmap.org/search"
params <- list(q = "AGS-27-Code", format = "json", limit = 1)

get_coordinates <- function(land, plz, ort, stn_hnr) {
  url <- paste0("https://nominatim.openstreetmap.org/search?country=", land, "&postalcode=", plz, "&city=", ort, "&street=", stn_hnr, "&format=json&limit=1")
  response <- GET(url)
  if (response$status_code == 200) {
    json <- content(response, "text")
    data <- fromJSON(json)
    if (length(data) > 0) {
      lat <- as.numeric(data[[1]]$lat)
      lon <- as.numeric(data[[1]]$lon)
      return(c(lat, lon))
    } else {
      warning(paste0("No results found for address ", stn_hnr, ", ", plz, " ", ort, ", ", land))
    }
  } else {
    warning(paste0("API request failed for address ", stn_hnr, ", ", plz, " ", ort, ", ", land))
  }
  return(NA)
}

# Anwenden der Funktion auf die Spalten
firmen$coords <- apply(firmen[1], 1, function(x) get_coordinates(x["land"], x["plz"], x["ort"], x["stn_hnr"]))



anteile <- personen %>% 
  group_by(geschlecht) %>% 
  summarize(n_ges = n()) %>% 
  mutate(anteil_ges = n / sum(n_ges))

ggplot(anteile, aes(x = geschlecht, y = anteil_ges)) +
  geom_bar(stat = "identity")

personen_relationen <- merge(x = personen, relationen_person_firma, by = "pers_id")
personen_relationen %>%
  group_by(geschlecht, funktion) %>%
  count(funktion, name = "funktion_abs_haeufigkeiten") %>%
  filter(funktion %in% c("Geschaeftsfuehrer"))

firmen_relationen <- merge(firmen, relationen_person_firma, by = "firm_id")
firmen_relationen %>% group_by(firm_id, pers_id, funktion) %>%
  filter(funktion %>% c("Geschaeftsfuehrer")) %>%
  count(pers_id) %>%
  summarize(avg_employees = mean(number_of_employees, na.rm = TRUE))

firmenname_laenge_zeit <- firmen_hist %>%
  mutate(registrations_year = year(registrations_datum)) %>%
  group_by(registrations_year) %>%
  summarize(avg_nchar = mean(nchar(unique(firmenname)), na.rm = TRUE))

ggplot(data = firmenname_laenge_zeit, mapping = aes(x = registrations_year, avg_nchar)) +
  geom_line()

# Geschlechter-Anteile nach Gründungsjahr
anteile <- personen %>% 
  group_by(geschlecht) %>% 
  summarize(n_ges = n()) %>% 
  mutate(anteil_ges = n / sum(n_ges))

ggplot(anteile, aes(x = geschlecht, y = anteil_ges)) +
  geom_bar(stat = "identity")
```

# Data wrangling
```{r}
extract_wz_code <- function(x) {
  lapply(x, function(code) {
    stringr::str_extract_all(code, "\\d+") %>%
      `[[`(1) %>%
      as.numeric() %>%
      min() %>%
      as.character() %>%
      substr(1, 2)
  })
}

branche_name <- c(
  "A" = "Land- und Forstwirtschaft, Fischerei ",
  "B" = "Bergbau und Gewinnung von Steinen und Erden",
  "C" = "Verarbeitendes Gewerbe",
  "E" = "Energieversorgung",
  "G" = "Handel; Instandhaltung und Reparatur von Kraftfahrzeugen",
  "H" = "Verkehr und Lagerei",
  "I" = "Gastgewerbe",
  "J" = "Information und Kommunikation",
  "K" = "Erbringung von Finanz- und Versicherungsdienstleistungen",
  "L" = "Grundstücks- und Wohnungswesen",
  "M" = "Erbringung von freiberuflichen, wissenschaftlichen und technischen Dienstleistungen",
  "N" = "Erbringung von sonstigen wirtschaftlichen Dienstleistungen",
  "O" = "Öffentliche Verwaltung, Verteidigung; Sozialversicherung",
  "P" = "Erziehung und Unterricht",
  "Q" = "Gesundheits- und Sozialwesen",
  "R" = "Kunst, Unterhaltung und Erholung",
  "T" = "Private Haushalte mit Hauspersonal; Herstellung von Waren und Erbringung von Dienstleistungen durch Private Haushalte für den Eigenbedarf ohne ausgeprägten Schwerpunkt",
  "U" = "Exterritoriale Organisationen und Körperschaften"
)

firmen <- firmen %>%
  # select(-c(
  #   "amtsgericht_plz", "amtsgericht_ort", "hr_nummer",
  #   "hr_nummer_alle", "hr_nummer_info", "gegenstand",
  #   "pubid_arr", "pdf_id_arr", "wz_code_text"
  # )) %>%
  mutate(
    branche_code = extract_wz_code(wz_code),
    branche_code = case_when(
      branche_code < 05 ~ "A",
      branche_code < 10 ~ "B",
      branche_code < 35 ~ "C",
      branche_code < 45 ~ "E",
      branche_code < 49 ~ "G",
      branche_code < 55 ~ "H",
      branche_code < 58 ~ "I",
      branche_code < 64 ~ "J",
      branche_code < 68 ~ "K",
      branche_code < 69 ~ "L",
      branche_code < 77 ~ "M",
      branche_code < 84 ~ "N",
      branche_code < 85 ~ "O",
      branche_code < 86 ~ "P",
      branche_code < 90 ~ "Q",
      branche_code < 97 ~ "R",
      branche_code < 99 ~ "T",
      branche_code == 99 ~ "U"
    ),
    branche_name = lapply(branche_code, function(x) branche_name[x]),
    mitarbeiter_year = stringr::str_extract(mitarbeiter_staffel, "\\d{4}"),
    mitarbeiter_range = stringr::str_extract(mitarbeiter_staffel, "\\d+-\\d+"),
    umsatz_year = stringr::str_extract(umsatz_staffel, "\\d{4}"),
    umsatz_range = stringr::str_extract(umsatz_staffel, "\\d+-\\d+")
)
```

# Diversity analysis
```{r diversity analysis}
# female representation in boards over time
relationen_person_firma_hist_fuehrung <- relationen_person_firma_hist %>%
  filter(funktion %in% c("Vorstandsvorsitzender", "Vorstand", "Direktor",
                         "Geschaeftsfuehrer", "Gruender", "Inhaber", "Kommanditist",
                         "Partner"))

relationen_fuehrung_hist <- merge(x = personen, 
                                   y = relationen_person_firma_hist_fuehrung, 
                                   by = "pers_id", 
                                   all.x = FALSE, 
                                   all.y = TRUE) %>%
  filter(geschlecht %in% c("m", "f"), beginn_jahr <= 2022)

relationen_fuehrung_adv <- merge(x = firmen, 
                                   y = relationen_fuehrung_hist, 
                                   by = "firm_id", 
                                   all.x = FALSE, 
                                   all.y = TRUE)


relationen_person_firma_fuehrung <- relationen_person_firma %>%
  filter(funktion %in% c("Vorstandsvorsitzender", "Vorstand", "Direktor",
                         "Geschaeftsfuehrer", "Gruender", "Inhaber", "Kommanditist",
                         "Partner"))

relationen_fuehrung <- merge(x = personen, 
                                   y = relationen_person_firma_fuehrung, 
                                   by = "pers_id", 
                                   all.x = FALSE, 
                                   all.y = TRUE) %>%
  filter(geschlecht %in% c("m", "f"))

relationen_fuehrung_adv_stat <- merge(x = firmen, 
                                   y = relationen_fuehrung, 
                                   by = "firm_id", 
                                   all.x = FALSE, 
                                   all.y = TRUE)


# Group data by year and gender, and count the number of occurrences
df_counts <- relationen_vorstand %>%
  group_by(beginn_jahr, geschlecht) %>%
  summarize(count = n())

# Calculate the total count for each year
df_totals <- df_counts %>%
  group_by(beginn_jahr) %>%
  summarize(total = sum(count))

# Calculate the relative frequency of each gender for each year
df_freq <- df_counts %>%
  left_join(df_totals, by = "beginn_jahr") %>%
  mutate(freq = count / total)

# Plot the results
ggplot(df_freq, aes(x = beginn_jahr, y = freq, color = geschlecht)) +
  geom_line() +
  scale_y_continuous(labels = scales::percent) +
  labs(x = "Year", y = "Relative Frequency", color = "Gender")

# average age in boards over time
```

# Function to plot gender diversity by "branche"
```{r}
diversity_branche <- function(df, branche) {
  df <- df %>%
    filter(branchen_code == !!branche)
  
  df_counts <- df %>%
  group_by(beginn_jahr, geschlecht) %>%
  summarize(count = n())

  # Calculate the total count for each year
  df_totals <- df_counts %>%
    group_by(beginn_jahr) %>%
    summarize(total = sum(count))
  
  # Calculate the relative frequency of each gender for each year
  df_freq <- df_counts %>%
    left_join(df_totals, by = "beginn_jahr") %>%
    mutate(freq = count / total)
  
  # Plot the results
  ggplot(df_freq, aes(x = beginn_jahr, y = freq, color = geschlecht)) +
    geom_line() +
    scale_y_continuous(labels = scales::percent) +
    labs(x = "Year", y = "Relative Frequency", color = "Gender")
  ggsave(paste("Plots/diversity_", branche, ".png", sep = ""),
         width = 12, height = 9)
}
```

```{r}
# Create Branchen Plots
branchen_codes <- unique(firmen$branchen_code)
for (branchen_code in branchen_codes) {
  diversity_branche(relationen_fuehrung_adv, branchen_code)
}
```

```{r}
ggplot(data = relationen_vorstand_adv, aes(y = beginn_jahr)) +
  geom_histogram() +
  coord_flip()

ggplot(data = relationen_vorstand_adv, aes(y = ende_jahr)) +
  geom_histogram() +
  coord_flip()

```

#  Analyse Diversität Firma nach PLZ
```{r}
relationen_fuehrung_adv_stat <- relationen_fuehrung_adv_stat %>%
  mutate(alter = 2023 - jahr) %>%
  filter(alter >= 0, alter <= 100)

relationen_fuehrung_adv_stat <- relationen_fuehrung_adv_stat %>%
  group_by(firm_id, pers_id) %>%
  slice(1)

relationen_fuehrung_adv_stat_div <- relationen_fuehrung_adv_stat %>%
  group_by(firm_id) %>%
  mutate(diversity_alter = min(c(max(alter) - min(alter)) / 50, 1),
         diversity_geschlecht = 1 - 2 * abs(0.5 - mean(geschlecht == "m")))
relationen_fuehrung_adv_stat_div$diversity_score  <-  (relationen_fuehrung_adv_stat_div$diversity_alter + relationen_fuehrung_adv_stat_div$diversity_geschlecht) / 2

firmen_diversität <- relationen_fuehrung_adv_stat_div %>% arrange((diversity_score))  %>% filter(mitarbeiter_range %in% c("51-500", "501-5000", "5001-50000")) %>% 
  group_by(firm_id) %>%
  filter(n() >= 2)

# relationen_fuehrung_adv_stat <- relationen_fuehrung_adv_stat %>%
#   group_by(firm_id) %>%
#   mutate(diversity_score = mean(min(c(max(alter) - min(alter)) / 50, 1), 1 - 2 * abs(0.5 - mean(geschlecht == "m"))))


relationen_fuehrung_adv_stat_div %>% arrange(desc(diversity_score))  %>% filter(mitarbeiter_range %in% c("501-5000", "5001-50000")) %>% select(firmenname, hr_nummer, diversity_alter, diversity_geschlecht, diversity_score, mitarbeiter_range)

relationen_fuehrung_adv_stat_div %>% arrange((diversity_score))  %>% filter(mitarbeiter_range %in% c("51-500", "501-5000", "5001-50000")) %>% 
  group_by(firm_id) %>%
  filter(n() >= 5) %>%
  select(firmenname, hr_nummer, diversity_alter, diversity_geschlecht, diversity_score, mitarbeiter_range)

relationen_fuehrung_adv_stat_div %>% arrange((diversity_score))  %>% filter(mitarbeiter_range %in% c("51-500", "501-5000", "5001-50000")) %>% 
  group_by(firm_id) %>%
  filter(n() >= 2) %>%
  select(firmenname, diversity_score, mitarbeiter_range) %>% distinct()

firmen_diversität <- relationen_fuehrung_adv_stat_div %>% arrange((diversity_score))  %>%
  group_by(firm_id) %>%
  filter(n() >= 2) %>% 
  slice(1)

firmen_diversität %>%
  group_by(mitarbeiter_range) %>%
  summarise(mean(diversity_score))

ggplot(data = firmen_diversität, mapping = aes(x = mitarbeiter_range, diversity_score)) +
  geom_()
```

